### ISSUE TITLE
语法高亮错误

### ISSUE THREAD

**Issue by archersmind** [starwing/vimrc#2]
Bro Xu, 那个括号匹配的语法高亮错误，怎么解决？一直在用你的vimrc，自己太懒一直没有系统的学习过。

![高亮错误](http://i.stack.imgur.com/8JT5b.png)

帮忙看看呗

谢谢 :smile:

**Comment by archersmind** [comment]
c/extra.vim 中的 line:11

```
syn match       cMathOperator     display "[-+\*/%=]"
```

这一行似乎有点BUG，会导致上面的问题。有空请看看啦！

**Comment by starwing** [comment]
好的，我看看~~多谢哈
